package:
  name: libsvm-kitware
  version: 3.1custom

source:
  git_url: https://github.com/Kitware/SMQTK
  git_tag: v0.2.1

requirements:
  build:
    - python

test:
  requires:
    - python
  imports:
    - svm
    - svmutil

about:
  home: https://github.com/Kitware/SMQTK/tree/master/TPL/libsvm-3.1-custom
  license: modified BSD
  summary: "A Library for Support Vector Machines - Customized by Kitware to add Solr support"
