package:
  name: libsvm-kitware
  version: 3.1custom

source:
  git_url: https://github.com/Kitware/SMQTK
  git_rev: v0.1

about:
  home: https://github.com/Kitware/SMQTK/tree/master/TPL/libsvm-3.1-custom
  license: modified BSD
