source:
  fn: OpenCV-2.4.2.tar.bz2
  md5: 059ef86fc1724d69b75832a0d2929ff5

build:
  number: 1

requirements:
  build:
    - cmake        [unix]
    - numpy
    - jpeg
    - zlib
    - libpng
  run:
    - python
    - numpy
    - jpeg
    - zlib         [unix]
    - libpng

about:
  home: http://opencv.willowgarage.com/wiki/
  license: BSD
