package:
  name: cloudpickle
  version: "0.1.1"

source:
  fn: cloudpickle-0.1.1.tar.gz
  url: https://pypi.python.org/packages/source/c/cloudpickle/cloudpickle-0.1.1.tar.gz
  md5: 47376a2fa209283b5e6d05b36eecdb5a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cloudpickle = cloudpickle:main
    #
    # Would create an entry point called cloudpickle that calls cloudpickle.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - cloudpickle

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cloudpipe/cloudpickle
  license: BSD License
  summary: 'Extended pickling support for Python objects'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
