package:
  name: groff
  version: 1.22.3

source:
  fn: groff-1.22.3.tar.gz
  url: https://ftp.gnu.org/gnu/groff/groff-1.22.3.tar.gz
  sha1: fjdkslfjdkslfj

requirements:
  build:
    - perl >=5.6.1
    - ghostscript
    - psutils
    - netpbm
  run:
    - perl >=5.6.1
    - ghostscript
    - psutils
    - netpbm

about:
  summary: Groff (GNU troff) is a typesetting system that reads plain text mixed with formatting commands and produces formatted output.
  home: https://www.gnu.org/software/groff/
  license: GPL
