package:
  name: atom-shell
  version: '0.13.3'
  
build:
  binary_relocation: false
  entry_points:
    - atomshell = atomshell:main

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/atom/atom-shell
  license: MIT
