package:
  name: r
  version: 3.1.1

source:
  fn: R-3.1.1.tar.gz
  url: http://cran.cnr.berkeley.edu/src/base/R-3/R-3.1.0.tar.gz
  patches:
    - share-make-vars.mk.patch

build:
  number: 3

requirements:
  build:
    - readline
    - system    [linux]
    - tk
    - zlib
    - gmp
    - gsl
    - cairo     [linux]
    - freeglut  [linux]
    - freetype
    - imaging
    - jpeg
    - libpng
    - libtiff
    - libxml2
    - libxslt
    - lxml
    - matplotlib
    - vtk

  run:
    - readline
    - system    [linux]
    - tk
    - zlib
    - gmp
    - gsl
    - cairo     [linux]
    - freeglut  [linux]
    - freetype
    - imaging
    - jpeg
    - libpng
    - libtiff
    - libxml2
    - libxslt
    - lxml
    - matplotlib
    - vtk

test:
  commands:
    - R -h
    - R --version
    - Rscript --version

about:
  home: http://www.r-project.org/
  license: GPL

# vim:set ts=8 sw=2 sts=2 tw=78 et:
