{% set version = '2.8.0' %}
{% set versionu = '2_8_0' %}
{% set pfx = 'm2w64-' if win else '' %}

package:
  name: rpy2
  version: "{{version}}"

source:
  fn: rpy2-{{version}}.tar.gz
  url: https://bitbucket.org/rpy2/rpy2/get/RELEASE_{{versionu}}.tar.bz2
  sha1: 39c574797a2212c87f053ee664f94c8246987b44
#  patches:
   # List any patch files here
   # - fix.patch

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    # Note, until the build env. is activated properly, you'll need posix in your
    # root env. too. Proper activation is in-progress though.
    - posix             # [win]
    - {{pfx}}toolchain  # [win]
    - python
    - r
    - setuptools
    - singledispatch    # [not (py34 or py35)]
    - six
    - readline          # [not win]

  run:
    - python
    - r
    - singledispatch    # [not (py34 or py35)]
    - six
    - readline          # [not win]

test:
  # Python imports
  imports:
    - rpy2
    - rpy2.interactive
    - rpy2.interactive.tests
    - rpy2.ipython
    - rpy2.ipython.tests
    - rpy2.rinterface
    - rpy2.rinterface.tests
    - rpy2.rlike
    - rpy2.rlike.tests
    - rpy2.robjects
    - rpy2.robjects.lib
    - rpy2.robjects.lib.tests
    - rpy2.robjects.tests

  commands:
    - python -m rpy2.tests

  requires:
    - ipython
    - r-survival
    - r-ggplot2
    - numpy
    - pandas

about:
  home: http://rpy.sourceforge.net
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'Python interface to the R language (embedded R)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
