package:
  name: scipy
  version: 0.15.1

source:
  fn: scipy-0.15.1.tar.gz
  url: https://pypi.python.org/packages/source/s/scipy/scipy-0.15.1.tar.gz
  md5: be56cd8e60591d6332aac792a5880110

requirements:
  build:
    - python
    - openblas
    - numpy

  run:
    - libgcc
    - python
    - openblas
    - numpy

build:
  number: 1
  string: py{{py}}np{{np}}_0o
  features:
    - openblas

about:
  home: https://www.scipy.org
  license: PSF
