package:
  name: pudb
  version: 2013.3.2

source:
  fn: pudb-2013.3.2.tar.gz

  url: http://pypi.python.org/packages/source/p/pudb/pudb-2013.3.2.tar.gz
  md5: aacca6e45b664914a1f514e3580d1d65

build:
  entry_points:
    - pudb = pudb.run:main  [py2k]
    - pudb3 = pudb.run:main [py3k]

  number: 1

requirements:
  build:
    - python
    - distribute
    - pygments
    - urwid

  run:
    - python
    - pygments
    - urwid

test:
  # Python imports
  imports:
    - pudb

  commands:
    - pudb --help  [py2k]
    - pudb3 --help [py3k]

about:
  home: http://pypi.python.org/pypi/pudb
  license: MIT License
