package:
  name: pudb
  version: 2013.3.5

source:
  fn: pudb-2013.3.5.tar.gz
  url: http://pypi.python.org/packages/source/p/pudb/pudb-2013.3.5.tar.gz
  md5: 532a9a919b943ccf01205451d51b55ab

build:
  entry_points:
    - pudb = pudb.run:main
    - pudb3 = pudb.run:main [py3k]

  number: 2

requirements:
  build:
    - python
    - distribute
    - pygments
    - urwid

  run:
    - python
    - pygments
    - urwid

test:
  # Python imports
  imports:
    - pudb

  commands:
    - pudb --help  [py2k]
    - pudb3 --help [py3k]

about:
  home: http://pypi.python.org/pypi/pudb
  license: MIT License
