package:
  name: gunicorn
  version: 17.5

source:
  fn: gunicorn-17.5.tar.gz
  url: https://pypi.python.org/packages/source/g/gunicorn/gunicorn-17.5.tar.gz
  md5: 32e4477ac20e1061c9860f466cc87a14
#  patches:
   # List any patch files here
   # - fix.patch

build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gunicorn = gunicorn:main
    #
    # Would create an entry point called gunicorn that calls gunicorn.main()
    - gunicorn=gunicorn.app.wsgiapp:run
    - gunicorn_django=gunicorn.app.djangoapp:run
    - gunicorn_paster=gunicorn.app.pasterapp:run


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - paste.deploy

test:
  # Python imports
  imports:
    - gunicorn

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - gunicorn --help
    - gunicorn_django --help
    - gunicorn_paster --help


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any test requirements here.  For example
    # - nose
    - paste

about:
  home: http://gunicorn.org
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
