package:
  name: wxpython
  version: 2.8.12.1

source:
  fn: wxPython-src-2.8.12.1.tar.bz2
  url: http://downloads.sourceforge.net/wxpython/wxPython-src-2.8.12.1.tar.bz2

requirements:
  build:
    - python

about:
  home: http://www.wxpython.org/
  license: wxWindows License
