
package:
    name: wxpython
    version: 2.8.12.1

source:
    fn: wxPython-src-2.8.12.1.tar.bz2
    url: http://downloads.sourceforge.net/wxpython/wxPython-src-2.8.12.1.tar.bz2

build:
    number: 0

requirements:
    build:
        - python
        - distribute

    run:
        - python

test:
    imports:
        - wxpython

about:
    home: http://www.wxpython.org
    license: wxWindows Licese

