package:
  name: pydas
  version: "0.1.0"

source:
  #git_tag: 0.1.0
  git_url: https://github.com/GreenGroup/PyDAS.git

requirements:
  build:
    - gcc
    - python
    - setuptools
    - cython
    - numpy
    - wget
  run:
    - libgcc
    - python
    - numpy

test:
  requires:
    - nose
  imports:
    - pydas
    - pydas.dassl
    - pydas.daspk
  commands:
    - cd $SRC_DIR/tests && nosetests *.py

about:
  home: http://github.com/GreenGroup/PyDAS
  license: MIT
  summary: "A Python wrapper to several differential algebraic system solvers, namely DASSL and DASPK."
