{% set pfx = 'm2w64-' if win else '' %}
{% set ver= '3.3.1' %}

package:
  name: r-base
  version: {{ ver }}

source:
  url: https://cran.r-project.org/src/base/R-3/R-{{ ver }}.tar.gz
  sha1: df853188d3e2b1c2d32393016401c432a5192c4d
  patches:
    - mac-unicode.patch # [osx]
    - 0002-Win32-Fix-trio-config-h-include-depth-issue.patch
    - 0003-Win32-Do-not-static-libgcc-link.patch              # This patch is only correct if using MSYS2's tcltk.
    - 0004-Win32-Use-TCL_VERSION_86.patch                     # This patch is only correct if using MSYS2's tcltk.
    - 0005-Win32-Extend-sqrt-NA_real_-hack-to-all-GCC-versions.patch
    - 0006-Win32-GCC-5.3-Fix-ISNAN-int-emits-UD2-insn.patch
    - 0007-Win32-MSYS2-ENV_CONV_EXCL_R_ARCH.patch
    - 0008-Darwin-set-DYLD_FALLBACK_LIBRARY_PATH.patch
    - 0009-R-3.3.0-Use-AC_SEARCH_LIBS-to-search-for-ncurses.patch
    - 0010-configure-Fix-typo-CPPLAGS.patch

build:
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

requirements:
  build:
    - posix                 # [win]
    - m2-texinfo-tex        # [win]
    - m2-texinfo            # [win]
    - m2-curl               # [win]
    - m2-p7zip              # [win]
    - readline              # [not win]
    - ncurses               # [not win]
    - cairo                 # [linux]
    - pango                 # [linux]
    - gcc                   # [not win]
    - jpeg                  # [not win]
    - curl                  # [not win]
    - {{pfx}}bzip2          # [not osx]
    - {{pfx}}libjpeg-turbo  # [win]
    - {{pfx}}toolchain      # [win]
    - {{pfx}}libiconv       # [win]
    - {{pfx}}gmp            # [win]
    - {{pfx}}fftw           # [win]
    - {{pfx}}xz             # [win]
    - xz 5.2.*              # [not win]
    - {{pfx}}mpfr           # [win]
    - {{pfx}}libsndfile     # [win]
    - {{pfx}}bwidget        # [win]
    - {{pfx}}tktable        # [win]
    - {{pfx}}tk
    - {{pfx}}zlib
    - {{pfx}}gsl
    - {{pfx}}libpng
    - {{pfx}}libtiff
    - {{pfx}}libxml2
    - {{pfx}}pcre

  run:
    - readline              # [not win]
    - ncurses               # [not win]
    - cairo                 # [linux]
    - pango                 # [linux]
    - libgcc                # [not win]
    - {{pfx}}gcc-libs       # [win]
    - jpeg                  # [not win]
    - curl                  # [not win]
    - {{pfx}}bzip2          # [not osx]
    - {{pfx}}libjpeg-turbo  # [win]
    - {{pfx}}libiconv       # [win]
    - {{pfx}}gmp            # [win]
    - {{pfx}}fftw           # [win]
    - {{pfx}}xz             # [win]
    - xz 5.2.*              # [not win]
    - {{pfx}}mpfr           # [win]
    - {{pfx}}libsndfile     # [win]
    - {{pfx}}bwidget        # [win]
    - {{pfx}}tktable        # [win]
    - {{pfx}}tk
    - {{pfx}}zlib
    - {{pfx}}gsl
    - {{pfx}}libpng
    - {{pfx}}libtiff
    - {{pfx}}libxml2
    - {{pfx}}pcre

test:
  commands:
    - R -h
    - R --version
    - Rscript --version
    - Rscript -e  'cat("ok\\n")'
    - open # [win]
    # There doesn't seem to be a way to test this one
    # - RSetReg # [win]
    - Rfe --help # [win]
    - Rterm --help # [win]
    - Rterm --version # [win]

about:
  home: http://www.r-project.org/
  license: GPL
