package:
  name: nikola
  version: !!str 7.0.1

source:
  fn: nikola-7.0.1.tar.gz
  url: https://pypi.python.org/packages/source/N/Nikola/nikola-7.0.1.tar.gz
  md5: c220c2bedf9c12770cf1311e9db211bd
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nikola = nikola:main
    #
    # Would create an entry point called nikola that calls nikola.main()

    - nikola = nikola.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - doit >=0.23.0
    - pygments
    - pillow >=2.0.0
    - python-dateutil
    - docutils
    - mako >=0.6
    - unidecode
    - lxml
    - yapsy
    - pyrss2gen
    - logbook
    - blinker
    - setuptools
    - natsort >=3.2.0

  run:
    - python
    - doit >=0.23.0
    - pygments
    - pillow >=2.0.0
    - python-dateutil
    - docutils
    - mako >=0.6
    - unidecode
    - lxml
    - yapsy
    - pyrss2gen
    - logbook
    - blinker
    - setuptools
    - natsort >=3.2.0

test:
  # Python imports
  imports:
    - nikola
    - nikola.plugins
    - nikola.plugins.command
    - nikola.plugins.compile
    - nikola.plugins.compile.ipynb
    - nikola.plugins.compile.markdown
    - nikola.plugins.compile.rest
    - nikola.plugins.task
    - nikola.plugins.task.sitemap
    - nikola.plugins.template

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - nikola --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://getnikola.com
  license:  MIT License
  summary: 'A modular, fast, simple, static website generator'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
