package:
  name: cvxopt
  version: 1.1.6

source:
  fn: 1.1.6.tar.gz
  url: https://github.com/cvxopt/cvxopt/archive/1.1.6.tar.gz
  patches:
  # List any patch files here
    - setup.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nltk = nltk:main
    #
    # Would create an entry point called nltk that calls nltk.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - atlas
    - python

  run:
    - atlas
    - python

test:
  # Python imports
  imports:
    - cvxopt

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://cvxopt.org/
  license: GNU General Public License (GPL)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
