package:
  name: gstreamer
  version: 1.6.0

source:
  fn: gstreamer-1.6.0.tar.xz
  url: http://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.6.0.tar.xz
  sha256: 52ef885647afef11c8b7645a9afefe04aa09e8971c4b932e7717872ab8a30fcc

about:
    home: http://gstreamer.freedesktop.org/
    license: LGPL

requirements:
  build:
    - bison
    - flex
    - glib
  
  run:
    - glib


