package:
  name: py
  version: 1.4.15

source:
  fn: py-1.4.15.tar.gz
  url: https://pypi.python.org/packages/source/p/py/py-1.4.15.tar.gz
  md5: b5afc772d242d2dbcf7a2fcf3080a799
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - py = py:main
    #
    # Would create an entry point called py that calls py.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - py

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pylib.readthedocs.org/
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
