package:
  name: swig
  version: 3.0.4

source:
  fn: swig-3.0.4.tar.gz
  url: http://prdownloads.sourceforge.net/swig/swig-3.0.4.tar.gz
  md5: 9cb8c0efda39dc6db5f85389e671fb59

build:
  detect_binary_files_with_prefix: True

requirements:
  build:
    - pcre
    - python
  run:
    - pcre

test:
  commands:
    - swig -help

about:
    home: http://www.swig.org/
    license: GPLv3
