package:
  name: pyqt
  version: "4.11.1"

source: # [unix]
  fn: PyQt-mac-gpl-4.11.1.tar.gz # [osx]
  url: http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.1/PyQt-mac-gpl-4.11.1.tar.gz # [osx]
  sha1: 9d7478758957c60ac5007144a0dc7f157f4a5836 # [osx]
  fn: PyQt-x11-gpl-4.11.1.tar.gz # [linux]
  url: http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.1/PyQt-x11-gpl-4.11.1.tar.gz # [linux]
  sha1: 83a0740545d51c179a1b316b664b0f9ff5e0f5af # [linux]
  patches: # [unix]
    - configure.patch # [unix]

requirements:
  build: # [unix]
    - python # [unix]
    - qt # [unix]
    - sip >=4.16.2 # [unix]

  run:
    - python
    - qt # [unix]
    - sip >=4.16.2

test:
  imports:
    - PyQt4

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: GPL
