package:
  name: ipython
  version: 0.13.2

source:
  fn: ipython-0.13.2.tar.gz
  url: http://pypi.python.org/packages/source/i/ipython/ipython-0.13.2.tar.gz
  md5: ead3b7eb70c653b537fb9d96d71b8b2a
  patches:
    - hugo.patch             [linux]

build:
  entry_points:
    - ipython3 = IPython.frontend.terminal.ipapp:launch_new_instance  [py3k]
    - ipython = IPython.frontend.terminal.ipapp:launch_new_instance   [win]
  osx_is_app: True           [py2k]

requirements:
  build:
    - python
    - distribute             [win or py3k]
    - pyreadline             [win]
  run:
    - python
    - pyreadline             [win]
    - python.app             [osx and py2k]

test:
  commands:
    - ipython -h             [py2k]
    - ipython3 -h            [py3k]
  imports:
    - IPython

about:
  home: http://ipython.org/
  license: BSD
