package:
  name: mpc
  version: 1.0.1

source:
  url: http://www.multiprecision.org/mpc/download/mpc-1.0.1.tar.gz
  fn: mpc-1.0.1.tar.gz

requirements:
  build:
    - gmp
    - mpfr
  run:
    - gmp
    - mpfr

about:
  home: http://www.multiprecision.org/
  license: GPL
