package:
    name: continuumweb
    version: 1.0.0

source:
    git_url: https://github.com/ContinuumIO/continuumweb.git

build:
    number: 1

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - continuumweb

about:
    home: https://github.com/ContinuumIO/continuumweb
    license: MIT
