package:
  name: sympy
  version: 0.7.3.rc1

source:
  fn: sympy-0.7.3.rc1.tar.gz                                                                            [py2k]
  url: https://github.com/sympy/sympy/releases/sympy-0.7.3.rc1/2178/sympy-0.7.3.rc1.tar.gz              [py2k]
  md5: 28c52ad74ed492cdec7d137f0df2e41b                                                                 [py2k]
  fn: sympy-0.7.2.rc1-py3.2.tar.gz                                                                      [py3k]
  url: https://github.com/sympy/sympy/releases/sympy-0.7.3.rc1/2176/sympy-0.7.3.rc1-py3.2.tar.gz        [py3k]
  md5: 539815bd5ed59d3935f692abd60d39ec                                                                 [py3k]

requirements:
  build:
    - python
  run:
    - python

about:
  home: http://sympy.org
  license: New BSD
