source:
  fn: sympy-0.7.2.tar.gz                                                  [py2k]
  url: http://pypi.python.org/packages/source/s/sympy/sympy-0.7.2.tar.gz  [py2k]
  md5: 480185006fb318f5c9bbd75b4cf9771d                                   [py2k]
  fn: sympy-0.7.2-py3.2.tar.gz                                                 [py3k]
  url: http://pypi.python.org/packages/source/s/sympy/sympy-0.7.2-py3.2.tar.gz [py3k]
  md5: a90621bf4c0678c35e67ed62a56196f1                                        [py3k]

requirements:
  build:
    - python
  run:
    - python

about:
  home: http://code.google.com/p/sympy/
  license: New BSD
