package:
  name: h5py
  version: 2.2.0

source:
  fn: h5py-2.2.0.tar.gz
  url: https://github.com/h5py/h5py/archive/2.2.0.tar.gz
  md5: 7456ff4b33a7d8581027acd0e92eb3fb

requirements:
  build:
    - python
    - numpy
    - hdf5
    - cython
  run:
    - python
    - numpy
    - hdf5         [unix]

about:
  home: http://www.h5py.org/
  license: New BSD (http://opensource.org/licenses/bsd-license.php)
