package:
  name: r-essentials
  version: 1.5.0

requirements:
  # Not really needed, but just to make sure that they are built
  build:
    - r-base >=3.3.2
    - r-recommended >=3.3.2
    - r-ggplot2 >=2.2.0
    - r-plyr >=1.8.4
    - r-reshape2 >=1.4.2
    - r-dplyr >=0.5.0
    - r-tidyr >=0.6.0
    - r-caret >=6.0_73
    - r-randomforest >=4.6_12
    - r-data.table >=1.10.0
    - r-quantmod >=0.4_7
    - r-shiny >=0.14.2
    - r-rmarkdown >=1.2
    - r-glmnet >=2.0_5
    - r-jsonlite >=1.1
    - r-zoo >=1.7_13
    - r-irkernel >=0.7.1
    - r-rbokeh >=0.5.0
    - r-formatr >=1.4
    - notebook >=4.2.3
  run:
    - r-base >=3.3.2
    - r-recommended >=3.3.2
    - r-ggplot2 >=2.2.0
    - r-plyr >=1.8.4
    - r-reshape2 >=1.4.2
    - r-dplyr >=0.5.0
    - r-tidyr >=0.6.0
    - r-caret >=6.0_73
    - r-randomforest >=4.6_12
    - r-data.table >=1.10.0
    - r-quantmod >=0.4_7
    - r-shiny >=0.14.2
    - r-rmarkdown >=1.2
    - r-glmnet >=2.0_5
    - r-jsonlite >=1.1
    - r-zoo >=1.7_13
    - r-irkernel >=0.7.1
    - r-rbokeh >=0.5.0
    - r-formatr >=1.4
    - notebook >=4.2.3

about:
  summary: "Some essential packages for working with R"
  license: Various
  license_family: Other
