package:
  name: skll
  version: 0.22.0

source:
  fn: skll-0.22.0.tar.gz
  url: https://pypi.python.org/packages/source/s/skll/skll-0.22.0.tar.gz
  md5: 9d50a134ddeb17cbb9ed31c804a492df
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - skll = skll:main
    #
    # Would create an entry point called skll that calls skll.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - python
    - setuptools
    - scikit-learn
    - six
    - prettytable
    - beautiful-soup
    - numpy
    - scipy
    - configparser [py2k]
    - futures [py2k]
    - logutils [py2k]

  run:
    - python
    - scikit-learn
    - six
    - prettytable
    - beautiful-soup
    - numpy
    - scipy
    - configparser [py2k]
    - futures [py2k]
    - logutils [py2k]

test:
  # Python imports
  imports:
    - skll

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/EducationalTestingService/skll
  license: GNU General Public License v3 (GPLv3)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
