package:
  name: pyne
  version: staging

source:
  git_tag: staging
  git_url: https://github.com/pyne/pyne.git
  

requirements:
  build:
    - python
    - cmake
    - cython
    - pytables
    - hdf5
    - numpy
    - scipy
  run:
    - python
    - hdf5
    - numpy
    - scipy
    - pytables
	
test:
  requires:
    - nose
  imports:
    - pyne
    - pyne._utils
    - pyne.ace
    - pyne.data
    - pyne.enrichment
    - pyne.jsoncpp
    - pyne.material
    - pyne.nucname
    - pyne.pyne_config
    - pyne.xs.models


about:
  home: http://pynesim.org/
  license: BSD
