package:
  name: spyder
  version: 2.3.5.1

source:
  fn:   spyder-2.3.5.1.zip
  url:  https://pypi.python.org/packages/source/s/spyder/spyder-2.3.5.1.zip
  md5:  23df6762819da48f6ce5ef6c3a83738a

build:
  osx_is_app: True

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - rope
    - pyflakes
    - pyzmq
    - ipython
    - pygments
    - jinja2
    - docutils
    - sphinx
    - pep8
    - pylint
    - pyqt
    - python.app      [osx]

test:
  commands:
    - spyder -h
  imports:
    - spyderlib

about:
  home: https://github.com/spyder-ide/spyder
  license: MIT
