package:
  name: spyder
  version: 2.3.6

source:
  fn:   spyder-2.3.6.zip
  https://pypi.python.org/packages/source/s/spyder/spyder-2.3.6.zip
  md5: ae4a5e5014cc8c86820b34ba53661847

build:
  noarch_python: True
  osx_is_app: True

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - pyqt
    - rope
    - pyflakes
    - jedi            0.8*
    - qtconsole
    - nbconvert
    - pygments
    - sphinx
    - pep8
    - psutil
    - pylint
    - python.app      [osx]

test:
  commands:
    - spyder -h
  imports:
    - spyderlib

about:
  home: https://github.com/spyder-ide/spyder
  license: MIT
