package:
  name: ipython-qtconsole
  version: 1.0.0a1

requirements:
  run:
    - python
    - ipython
    - pyside

app:
  entry: ipython qtconsole
  icon: ipy.png
  summary: IPython QtConsole
  type: desk

about:
  home: http://ipython.org/
  license: BSD
