package:
  name: pycairo
  version: 1.10.0

source:
  fn:  py2cairo-1.10.0.tar.bz2                                       [py27]
  url: http://cairographics.org/releases/py2cairo-1.10.0.tar.bz2     [py27]
  md5: 20337132c4ab06c1146ad384d55372c5                              [py27]
  patches:
    - font.patch       [win and py27]
    - matrix.patch     [win and py27]
    - surface.patch    [win and py27]

requirements:
  build:
    - cairo
    - python
  run:
    - cairo
    - python

test:
  imports:
    - cairo
    - cairo._cairo

about:
  home: http://cairographics.org/pycairo/
  license: LGPL 2.1, MPL 1.1
  summary: Pycairo is a set of Python bindings for the cairo graphics library
