package:
  name: openturns
  version: 1.5rc1

source:
    svn_url: https://svn.openturns.org/openturns/tags/openturns-1.5rc1 # [not win]
    url: http://downloads.sourceforge.net/openturns/openturns/openturns-1.5rc1/openturns-1.5rc1-py2.7-i686.exe # [win32 and py27]
    url: http://downloads.sourceforge.net/openturns/openturns/openturns-1.5rc1/openturns-1.5rc1-py2.7-x86_64.exe # [win64 and py27]
    fn: openturns-1.5rc1-py2.7-i686.exe # [win32 and py27]
    fn: openturns-1.5rc1-py2.7-x86_64.exe # [win64 and py27]

build:
    number: 2

requirements:
    build:
        - python
        - cmake         # [not win]
        - swig          # [not win]
        - boost         # [not win]
        - lapack        # [not win]
        - libxml2       # [not win]
        - muparser      # [not win]
        - tbb           # [not win]

    run:
        - python
        - matplotlib
        - lapack        # [not win]
        - libxml2       # [not win]
        - muparser      # [not win]
        - tbb           # [not win]

test:
    imports:
      - openturns
      - openturns.viewer

about:
    home: http://openturns.org/
    license: GNU Lesser General Public License (LGPL)
