package:
  name: openturns
  version: 1.6rc1

source:
  fn: openturns-1.6rc1.tar.bz2 # [not win]
  url: http://downloads.sourceforge.net/openturns/openturns/openturns-1.6rc1/openturns-1.6rc1.tar.bz2 # [not win]
  sha1: e424323b8c32e638cee0b3630fc3d531334bf419 # [not win]

  fn: openturns-1.6rc1-py2.7-i686.exe # [win32 and py27]
  url: http://downloads.sourceforge.net/openturns/openturns/openturns-1.6rc1/openturns-1.6rc1-py2.7-i686.exe # [win32 and py27]
  sha1: 125fa22022179f92369dd89349e5cb4c9044578b # [win32 and py27]

  fn: openturns-1.6rc1-py2.7-x86_64.exe # [win64 and py27]
  url: http://downloads.sourceforge.net/openturns/openturns/openturns-1.6rc1/openturns-1.6rc1-py2.7-x86_64.exe # [win64 and py27]
  sha1: 7206dd3d72c3235753dc16bd49ffb27ffc827911 # [win64 and py27]

  fn: openturns-1.6rc1-py2.7-i686.exe # [win32 and py34]
  url: http://downloads.sourceforge.net/openturns/openturns/openturns-1.6rc1/openturns-1.6rc1-py2.7-i686.exe # [win32 and py34]
  sha1: 7f124d373ac5f79202a35399b5553c296aa204ea # [win32 and py34]

  fn: openturns-1.6rc1-py2.7-x86_64.exe # [win64 and py34]
  url: http://downloads.sourceforge.net/openturns/openturns/openturns-1.6rc1/openturns-1.6rc1-py2.7-x86_64.exe # [win64 and py34]
  sha1: 8843c8a9ad595985850d2f5ba4804d26e4f23702 # [win64 and py34]

build:
  number: 0

requirements:
  build:
    - python
    - cmake         # [not win]
    - swig          # [not win]
    - boost         # [not win]
    - lapack        # [not win]
    - libxml2       # [not win]
    - muparser      # [not win]
    - tbb           # [not win]

  run:
    - python
    - matplotlib
    - lapack        # [not win]
    - libxml2       # [not win]
    - muparser      # [not win]
    - tbb           # [not win]

test:
  imports:
    - openturns
    - openturns.viewer

about:
  home: http://openturns.org/
  license: GNU Lesser General Public License (LGPL)
