package:
  name: astor
  version: "0.5"

source:
  fn: astor-0.5.tar.gz
  url: https://pypi.python.org/packages/source/a/astor/astor-0.5.tar.gz
  md5: 0fa627a7f14e02566e941ec782c03bfc
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - astor = astor:main
    #
    # Would create an entry point called astor that calls astor.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - astor

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/berkerpeksag/astor
  license: BSD License
  summary: 'Read/rewrite/write Python ASTs'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
