package:
  name: r
  version: 3.2.3

about:
  home: https://mran.revolutionanalytics.com/open/
  license: GPL
  license_file: COPYING
  summary: Microsoft R Open

source:
  url: https://mran.revolutionanalytics.com/install/mro/3.2.3/MRO-3.2.3-win.exe   [win]
  fn: rro.exe   [win]
  
  url: https://mran.revolutionanalytics.com/install/mro/3.2.3/MRO-3.2.3-OSX.pkg  [osx]
  fn: rro.pkg   [osx]

  #url: https://mran.revolutionanalytics.com/install/mro/3.2.3/MRO-3.2.3.el5.x86_64.rpm   [linux]
  #fn: rro.rpm   [linux]

  git_url: https://github.com/RevolutionAnalytics/RRO.git   [linux]
  git_rev: MRO-3.2.3   [linux]

build:
  rpaths:
    - lib/R/lib
    - lib

requirements:
  build:
    - icu   [linux]
    - libpng  [linux]
    - readline   [linux]
    - libtiff   [linux]
    - libgfortran  [linux]
    - cairo    [linux]
    - pango   [linux]
  run:
    - icu   [linux]
    - libpng  [linux]
    - readline   [linux]
    - libtiff   [linux]
    - libgfortran  [linux]
    - cairo    [linux]
    - pango   [linux]

test:
  commands:
#    - R -e "library()"

#libpng
#libjpeg
#readline
#libtiff
#gcc
#make
#gcc-gfortran
#ghostscript-fonts
#libgfortran
#cairo
#curl
#libicu
#pango
#libSM
#libXt
#libXmu
#zip
#info
