package:
  name: drmaa
  version: 0.7.5

source:
  fn: drmaa-0.7.5.tar.gz
  url: https://pypi.python.org/packages/source/d/drmaa/drmaa-0.7.5.tar.gz
  md5: 602d4ba915cb91fd0bb7319d147cf775

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - drmaa

about:
  home: http://drmaa-python.googlecode.com
  license: BSD License
