package:
  name: drmaa
  version: 0.7.2

source:
  fn: drmaa-0.7.2.tar.gz
  url: https://pypi.python.org/packages/source/d/drmaa/drmaa-0.7.2.tar.gz
  md5: f06717f2874c92cd8d946ba9b1bc27cf

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - drmaa

about:
  home: http://drmaa-python.googlecode.com
  license: BSD License
