package:
  name: drmaa
  version: 0.7.3

source:
  fn: drmaa-0.7.3.tar.gz
  url: https://pypi.python.org/packages/source/d/drmaa/drmaa-0.7.3.tar.gz
  md5: cbc2f07b63d5e95a98348c45e085733f

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - drmaa

about:
  home: http://drmaa-python.googlecode.com
  license: BSD License
