package:
  name: sip
  version: 4.16.3

source:
  fn: sip-4.16.3.tar.gz # [unix]
  url: http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.3/sip-4.16.3.tar.gz # [unix]
  sha1: 7c4079d164ccbfe4a5274eaeebe8e3cc86e3a75a # [unix]
  fn: sip-4.16.3.zip # [win]
  url: http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.3/sip-4.16.3.zip # [win]
  sha1: 8f77e5edb19ffac5e162f1fe336428ec3c2d9580 # [win]

requirements:
  build:
    - python
    - python.app # [osx]

  run:
    - python

test:
  imports:
    - sip

  files:
    - test

  commands:
    - sip -c test test/word.sip

about:
  home: http://www.riverbankcomputing.com/software/sip/intro
  license: GPL
