package:
  name: sip
  version: 4.16.2

source:
  fn: sip-4.16.2.tar.gz
  url: http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.2/sip-4.16.2.tar.gz
  sha1: 4d3ebce6ec7c31d8a862a6ee307a5f6c3e67349b
  fn: sip-4.16.2.zip
  url: http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.2/sip-4.16.2.zip
  sha1: 44c50fba4a65ae7b67ba5d469da1560e7a614f07

requirements:
  build:
    - python
    - python.app # [osx]

  run:
    - python

test:
  imports:
    - sip

  files:
    - test

  commands:
    - sip -c test test/word.sip

about:
  home: http://www.riverbankcomputing.com/software/sip/intro
  license: GPL
