package:
  name: ipython_memwatcher
  version: "0.2.1"

source:
  fn: ipython_memwatcher-0.2.1.tar.gz
  url: https://pypi.python.org/packages/source/i/ipython_memwatcher/ipython_memwatcher-0.2.1.tar.gz
  md5: 2b266a05e22825f8e3676ec341e3861f
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ipython_memwatcher = ipython_memwatcher:main
    #
    # Would create an entry point called ipython_memwatcher that calls ipython_memwatcher.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - ipython >=2.1
    - memory_profiler

  run:
    - python
    - ipython >=2.1
    - memory_profiler

test:
  # Python imports
  imports:
    - ipython_memwatcher

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/FrancescAlted/ipython_memwatcher
  license: BSD 2-Clause
  summary: 'ipython_memwatcher: display memory usage during IPython execution'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
