package:
  name: binaryornot
  version: !!str 0.3.0

source:
  fn: binaryornot-0.3.0.tar.gz
  url: https://pypi.python.org/packages/source/b/binaryornot/binaryornot-0.3.0.tar.gz
  md5: 8f5bdbeb5ca31075582b42fdf4ce28f5
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - binaryornot

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/audreyr/binaryornot
  license: BSD License
  summary: 'Ultra-lightweight pure Python package to check if a file is binary or text.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
