package:
  name: gridmap
  version: 0.11.2

source:
  fn: gridmap-0.11.2.tar.gz
  url: https://pypi.python.org/packages/source/g/gridmap/gridmap-0.11.2.tar.gz
  md5: a98d48da0921a6d95e5d827d1f4e2da1

build:
  entry_points:
    - gridmap_web = gridmap.web:main
  number: 1

requirements:
  build:
    - python
    - setuptools
    - drmaa
    - pyzmq
    - psutil
    - cherrypy

  run:
    - python
    - drmaa
    - pyzmq
    - psutil
    - cherrypy

test:
  # Python imports
  imports:
    - gridmap

  commands:
    - gridmap_web --help

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/EducationalTestingService/gridmap
  license: GNU General Public License v3 (GPLv3)
