package:
  name: gridmap
  version: 0.12.0

source:
  fn: gridmap-0.12.0.tar.gz
  url: https://pypi.python.org/packages/source/g/gridmap/gridmap-0.12.0.tar.gz
  md5: 4ef6ffceed88b846479c079a822252da

build:
  entry_points:
    - gridmap_web = gridmap.web:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - drmaa
    - pyzmq
    - psutil
    - cherrypy

  run:
    - python
    - drmaa
    - pyzmq
    - psutil
    - cherrypy

test:
  # Python imports
  imports:
    - gridmap

  commands:
    - gridmap_web --help

about:
  home: http://github.com/EducationalTestingService/gridmap
  license: GNU General Public License v3 (GPLv3)
