package:
  name: gridmap
  version: 0.11.3

source:
  fn: gridmap-0.11.3.tar.gz
  url: https://pypi.python.org/packages/source/g/gridmap/gridmap-0.11.3.tar.gz
  md5: b7258e5bb0a56aed99e16fb60688c47c

build:
  entry_points:
    - gridmap_web = gridmap.web:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - drmaa
    - pyzmq
    - psutil
    - cherrypy

  run:
    - python
    - drmaa
    - pyzmq
    - psutil
    - cherrypy

test:
  # Python imports
  imports:
    - gridmap

  commands:
    - gridmap_web --help

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/EducationalTestingService/gridmap
  license: GNU General Public License v3 (GPLv3)
