package:
  name: opencv
  version: 2.4.5

source:
  fn: opencv-2.4.5.tar.gz
  url: http://filer/src/opencv-2.4.5.tar.gz
  md5: 8eac87462c7bec8b89021b723207c623

build:
  number: 1

requirements:
  build:
    - cmake        [unix]
    - numpy
    - jpeg
    - zlib
    - libpng
  run:
    - python
    - numpy
    - jpeg
    - zlib         [unix]
    - libpng

test:
  commands:
    - python delaunay.py

about:
  home: http://opencv.willowgarage.com/wiki/
  license: BSD
