package:
  name: veusz
  version: 1.17.1

source:
  git_url: https://github.com/jeremysanders/veusz.git
  git_tag: veusz-1.17.1
  
requirements: 
  build:
    - python

  run:
    - python
    - numpy
  