package:
  name: qt
  version: 4.8.4

source:
  url: http://filer/src/qt-everywhere-opensource-src-4.8.4.tar.gz
  md5: 89c5ecba180cae74c66260ac732dc5cb

build:
  number: 1

about:
    home: http://qt-project.org
    license: LGPL
