package:
  name: tbb
  version: 4.4

source:
  fn: tbb44_20150728oss_src.tgz
  url: https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb44_20150728oss_src.tgz
  md5: 2ef1d8cb790324c09aa17360d75dd619 

requirements:
  build:
    - python

about:
  home: http://www.threadingbuildingblocks.org
  license: GPL v2
