package:
  name: pymc
  version: 2.3

source:
  git_url: https://github.com/pymc-devs/pymc.git

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - pydot

test:
  imports:
    - pymc

  requires:
    - nose

about:
  home: https://github.com/pymc-devs/pymc
  license: Academic Free License (http://opensource.org/licenses/AFL-3.0)
