package:
  name: libpng
  version: 1.6.17

source:
  fn: libpng-1.6.17.tar.gz
  url: http://sourceforge.net/projects/libpng/files/libpng15/1.6.17/libpng-1.6.17.tar.gz/download
  md5: 134282f1752dcf4cd81a37b8ff421cef

requirements:
  build:
    - zlib

about:
  home: http://www.libpng.org/pub/png/libpng.html
  license: Open Source (http://www.libpng.org/pub/png/src/libpng-LICENSE.txt)
