{% set version = '1.5.0' %}

package:
  name: matplotlib-tests
  version: {{ version }}

source:
  git_url: https://github.com/matplotlib/matplotlib.git
  git_rev: v1.5.x

requirements:
  build:
    - matplotlib =={{ version }}

  run:
    - matplotlib =={{ version }}

about:
  home: http://matplotlib.sourceforge.net/
  license: PSF-based (http://matplotlib.sourceforge.net/users/license.html)
