package:
  name: matplotlib-tests
  version: 1.5.0

source:
  git_url: https://github.com/matplotlib/matplotlib.git
  git_rev: v1.5.x

requirements:
  build:
    - matplotlib ==1.5.0

  run:
    - matplotlib ==1.5.0

about:
  home: http://matplotlib.sourceforge.net/
  license: PSF-based (http://matplotlib.sourceforge.net/users/license.html)
