package:
  name: vtk
  version: 6.0.0

source:
  fn: vtk-6.0.0.tar.gz
  url: http://www.vtk.org/files/release/6.0/vtk-6.0.0.tar.gz

requirements:
  build:
    - cmake        [unix]
    - python

test:
  requires:
    - python

  imports:
    - vtk

about:
  home: http://www.vtk.org/
  license: BSD
