package:
  name: vtk
  version: 5.10.1

source:
  fn: vtk-5.10.1.tar.gz
  url: http://www.vtk.org/files/release/5.10/vtk-5.10.1.tar.gz

requirements:
  build:
    - cmake        [unix]
    - python

test:
  requires:
    - python

  imports:
    - vtk

about:
  home: http://www.vtk.org/
  license: BSD
