package:
  name: twitter
  version: 1.10.2

source:
  fn: twitter-1.10.2.tar.gz
  url: https://pypi.python.org/packages/source/t/twitter/twitter-1.10.2.tar.gz
  md5: 8bff1167b3886c759ee76afa8b52267e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - twitter = twitter:main
    #
    # Would create an entry point called twitter that calls twitter.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - distribute

test:
  # Python imports
  imports:
    - twitter

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://mike.verdone.ca/twitter/
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
