package:
    name: freeimage
    version: 3.17.0
    # note: also update version in run_test.py
    # note: On windows, needs VCOMP120.DLL, so this needs to be installed:
    #   http://www.microsoft.com/en-us/download/details.aspx?id=40784

source:
    fn: FreeImage3170.zip
    url: http://optimate.dl.sourceforge.net/project/freeimage/Source%20Distribution/3.17.0/FreeImage3170.zip
    md5: 459e15f0ec75d6efa3c7bd63277ead86
    
    patches:
        - Makefile.osx.patch  # [osx]
        - vs2010_omp.patch  # [win and py3k]

build:
    number: 1

test:
    requires:
        - python
    commands:
        - python run_test.py

about:
    home: http://freeimage.sourceforge.net/
    license: GPLv2 and FreeImage Public License
