package:
  name: cmake
  version: 3.1.3

source:
  fn: cmake-3.1.3.tar.gz
  url: http://www.cmake.org/files/v3.1/cmake-3.1.3.tar.gz
  md5: 5697a77503bb5636f4b4057dcc02aa32

test:
  commands:
    - cmake --help

about:
  home: http://www.cmake.org/
  license: BSD
