package:
  name: cmake
  version: 3.1.1

source:
  fn: cmake-3.1.1.tar.gz
  url: http://www.cmake.org/files/v3.1/cmake-3.1.1.tar.gz
  md5: d1c5176d111f6adec7aafb0afa00b6ec

test:
  commands:
    - cmake --help

about:
  home: http://www.cmake.org/
  license: BSD
