package:
  name: cmake
  version: 3.1.0

source:
  fn: cmake-3.1.0.tar.gz
  url: http://www.cmake.org/files/v3.1/cmake-3.1.0.tar.gz
  md5: 6da9011024a215073c3b390e9ed6ee21

test:
  commands:
    - cmake --help

about:
  home: http://www.cmake.org/
  license: BSD
