package:
  name: raml
  version: 0.0.0

build:
  number: 0
  # Windows has issues updating stuff if conda is using files itself.  Copy rather than link.
  no_link: .*\.(pyd|dll)        [win]

source:
  hg_url: ssh://hg@bitbucket.org/kalefranz/yaml
  hg_tag: tip

requirements:
  build:
    - python
    - cython
    - yaml
  run:
    - python
    - yaml

test:
  requires:
    - python
    - pytest
  imports:
    - raml
    # - _raml   [not (win and py3k)]  # this fails right now but should not

about:
  home: https://bitbucket.org/ruamel/yaml
  license: MIT
