package:
  name: glibc
  version: 2.14

source:
  fn: glibc-2.14.tar.xz
  url: http://gnu.spinellicreations.com/libc/glibc-2.14.tar.xz
  sha1: 175df29814b1eee3c9e68dd721c8f71c7b5e2c2e

about:
  home: http://www.gnu.org/software/libc/
  license: LGPL
  summary: "Any Unix-like operating system needs a C library: the library which defines the ``system calls'' and other basic facilities such as open, malloc, printf, exit..."
