package:
  name: pyqt5
  version: 5.3.2

source:
  fn: PyQt-gpl-5.3.2.zip # [win]
  url: http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.3.2/PyQt-gpl-5.3.2.zip # [win]
  sha1: e8a0a1db25cbbf14bedca976f6ffb15dac2ecc35 # [win]
  fn: PyQt-gpl-5.3.2.tar.gz # [unix]
  url: http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.3.2/PyQt-gpl-5.3.2.tar.gz # [unix]
  sha1: bb34d826a50b0735d1319dc51be6a094ba64b800 # [unix]


requirements:
  build:
    - python
    - qt5 >=5.3.0
    - sip >=4.16.2
    - jom # [win]

  run:
    - python
    - qt5 >=5.3.0
    - sip >=4.16.2

test:
  imports:
    - PyQt5.QtCore

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: GPL
