package:
  name: pyqt5
  version: 5.3.1

source:
  fn: PyQt-gpl-5.3.1.zip # [win]
  url: http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.3.1/PyQt-gpl-5.3.1.zip # [win]
  sha1: 446ff0f29f5fd6f7fbadb5a9b36ef8cced10a322 # [win]
  fn: PyQt-gpl-5.3.1.tar.gz # [unix]
  url: http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.3.1/PyQt-gpl-5.3.1.tar.gz # [unix]
  sha1: c3554c33cfe589afb3e3a4ca2ad87e325da30945 # [unix]


requirements:
  build:
    - python
    - qt5 >=5.3.0
    - sip >=4.16.2
    - jom # [win]

  run:
    - python
    - qt5 >=5.3.0
    - sip >=4.16.2

test:
  imports:
    - PyQt5

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: GPL
