package:
  name: smqtk
  version: "0.2.1"

source:
  git_url: https://github.com/Kitware/SMQTK.git
  git_tag: v0.2.1
  patches:
    - path-pass-through.patch

requirements:
  build:
    - cmake
    - flann
    - libsvm-kitware
    - python
  run:
    - flann
    - flask
    - flask-login
    - libsvm-kitware
    - numpy
    - pillow
    - pymongo
    - python
    - requests
    - scikit-learn
    - scipy

test:
  imports:
    - smqtk
  requires:
    - mock
    - nose
    - nose-exclude

about:
  home: https://github.com/Kitware/SMQTK
  license: MIT
  summary: "Python toolkit for pluggable algorithms and data structures for multimedia-based machine learning"
