package:
  name: r
  version: 3.1.2

source:
  fn: R-3.1.2.tar.gz # [not win]
  url: http://cran.cnr.berkeley.edu/src/base/R-3/R-3.1.2.tar.gz # [not win]
  sha1: 93809368e5735a630611633ac1fa99010020c5d6 # [not win]
  patches: # [not win]
    - share-make-vars.mk.patch # [not win]

  fn: R-3.1.2-win.exe # [win]
  url: http://cran.r-project.org/bin/windows/base/R-3.1.2-win.exe # [win]
  md5: 9e3c0cd6311355e0d5f8e1085b288361 # [win]

build:
  rpaths:
    - lib/R/lib/
    - lib/
  number: 2 # [linux]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - readline  # [not win]
    - ncurses   # [not win]
    - tk        # [not win]
    - zlib      # [not win]
    - gsl       # [not win]
    - cairo     # [linux]
    - pango     # [linux]
    - jpeg      # [not win]
    - libpng    # [not win]
    - libtiff   # [not win]
    - libxml2 # Not really sure if libxml2 is needed [not win]
    - gcc       # [not win]
    - pcre      # [not win]


  run:
    - readline  # [not win]
    - ncurses   # [not win]
    - tk        # [not win]
    - zlib      # [not win]
    - cairo     # [linux]
    - pango     # [linux]
    - jpeg      # [not win]
    - libpng    # [not win]
    - libtiff   # [not win]
    - libxml2   # [not win]
    - gcc       # [not win]
    - pcre      # [not win]

test:
  commands:
    - R -h
    - R --version
    - Rscript --version
    - Rscript -e  "cat('ok')"

about:
  home: http://www.r-project.org/
  license: GPL
