# This package is for OS X and Linux only. On Windows, r-recommended is part of r, and there is no r-core.
package:
  name: r
  version: 3.1.2

build:
  number: 3

requirements:
  run:
    - r-base
    - r-recommended
