package:
  name: nlopt
  version: 2.4.2

build:        # [not win]
  number: 1   # [not win]

requirements:
  build:
    - gcc     # [not win]
    - r       # [win]

source:
  fn: nlopt-2.4.2.tar.gz
  url: http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
