package:
  name: ipython-notebook
  version: 0.13.2

requirements:
  run:
    - python
    - ipython
    - pyzmq
    - tornado

app:
  entry: ipython notebook        [not osx]
  icon: ipynb_icon_64x64.png
  summary: IPython Notebook
  type: web
  cli_opts:                      [not osx]
    - name: port                 [not osx]
      args: --port %s            [not osx]
      default: 8080              [not osx]
      summary: Server port ...   [not osx]
  entry: open ipython_osx.command    [osx]

build:
  number: 1                          [osx]

about:
  home: http://ipython.org/notebook.html
  license: BSD
