package:
  name: ipython-notebook
  version: 1.0.0a1

requirements:
  run:
    - python
    - ipython
    - pyzmq
    - tornado
    - jinja2

app:
  icon: ipynb_icon_64x64.png
  summary: IPython Notebook
  type: web
  entry: open ${PREFIX}/bin/ipython_mac.command

about:
  home: http://ipython.org/notebook.html
  license: BSD
