package:
  name: netpbm
  version: 10.68

source:
  # See http://netpbm.svn.sourceforge.net/viewvc/netpbm/
  svn_url: http://svn.code.sf.net/p/netpbm/code/advanced
  svn_rev: 2294

requirements:
  build:
    - jpeg
    - libtiff
    - libpng
    - zlib
  run:
    - jpeg
    - libtiff
    - libpng
    - zlib

about:
  home: http://netpbm.sourceforge.net/
  summary: Netpbm is a toolkit for manipulation of graphic images, including conversion of images between a variety of different formats.
  license: GPL
